import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { cn } from "@/shared/lib";

import "./globals.css";
import { Toaster } from "@/shared/ui";

import { ApolloProvider } from "./providers/apollo.provider";
import { ThemeProvider } from "./providers/theme.provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: {
    template: "%s | Optix",
    default: "Dashboard | Optix",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.variable)}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ApolloProvider>{children}</ApolloProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
